databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog
    plan: free

services:
  - type: web
    name: django-blog
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_project.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: SECRET_KEY
        value: "GSf6DXB6Q0NEPNFh4AePilCEEyvIWSYpO8XPWD3LBGl0oHFDPCV1Vn9r9vd0nOdczyM"
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
    autoDeploy: true
